### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by liviro411** [dimaryaz/jdmtool#1]
Hi

I have tried to download the database for a G1000NXI system. I got an error trying to download "Europe IFR" and "Europe VFR":

hbu@laptophbu2:~> jdmtool list
ID  Name                                                                    Cycle  Start Date  End Date    Downloaded
 0  NavData Coverage Garmin G1000 Central Europe                             2303  2023-03-23  2023-04-20            
 1  Airport Directory Garmin G1000 AC-U-KWIK International                   23D1  2023-02-23  2023-04-20            
 2  SafeTaxi Coverage Garmin G1000 Europe                                    23S1  2023-02-23  2023-04-20            
 3  Terrain 4.9as Coverage Garmin G1000 SW v.15.00 or Newer Worldwide        20T1  2020-08-10  2024-04-08            
 4  NavData Garmin G1000 NXi, Perspective + Central Europe                   2303  2023-03-23  2023-04-20            
 5  Obstacles Garmin G1000 NXi, Perspective + Worldwide                      23B1  2023-02-23  2023-04-20            
 6  Basemap Coverage Garmin G1000 NXi Perspective + Worldwide                22M1  2022-04-15  2024-04-08            
 7  Europe IFR                                                              202307.1  2023-03-31  2023-04-14            
 8  Europe VFR                                                              202307.1  2023-03-31  2023-04-14            
hbu@laptophbu2:~> jdmtool info 0
Aircraft Manufacturer:        DIAMOND
Aircraft Model:               DA42, TWINSTAR
Aircraft Tail Number:         HBLVR

Avionics:                     Garmin G1000, G900X, G950, Perspective, Prodigy
Coverage:                     Central Europe
Service Type:                 NavData
Service Code:                 DGA03553
Service ID:                   33102448
Service Renewal Date:         2023-10-28 00:00:00

Version:                      2303
Version Start Date:           2023-03-23 06:00:00
Version End Date:             2023-04-20 06:00:00

Next Version:                 2304
Next Version Available Date:  2023-04-10 06:00:00
Next Version Start Date:      2023-04-20 06:00:00

File Name:                    dga035_2303_29114daf.zip
File Size:                    10894874
File CRC32:                   29114daf
hbu@laptophbu2:~> jdmtool download 0
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.9M/10.9M [00:04<00:00, 2.20MB/s]
Downloaded to /home/hbu/.local/share/jdmtool/downloads/dga035_2303_29114daf.zip
hbu@laptophbu2:~> jdmtool download 1
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.75M/4.75M [00:04<00:00, 967kB/s]
Downloaded to /home/hbu/.local/share/jdmtool/downloads/dgd203_23d1_213c01a6.zip
hbu@laptophbu2:~> jdmtool download 2
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12.7M/12.7M [00:05<00:00, 2.43MB/s]
Downloaded to /home/hbu/.local/share/jdmtool/downloads/dgs235_23s1_5d913c72.zip
hbu@laptophbu2:~> jdmtool download 3
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.60G/3.60G [08:08<00:00, 7.37MB/s]
Downloaded to /home/hbu/.local/share/jdmtool/downloads/DGT208_20t1_9120A9F4.zip
hbu@laptophbu2:~> jdmtool download 4
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.9M/10.9M [00:04<00:00, 2.23MB/s]
Downloaded to /home/hbu/.local/share/jdmtool/downloads/dga035_2303_29114daf.zip
hbu@laptophbu2:~> jdmtool download 5
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24.0M/24.0M [00:06<00:00, 3.72MB/s]
Downloaded to /home/hbu/.local/share/jdmtool/downloads/dgo001_23b1_d58f03a8.zip
hbu@laptophbu2:~> jdmtool download 6
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38.5M/38.5M [00:07<00:00, 5.18MB/s]
Downloaded to /home/hbu/.local/share/jdmtool/downloads/dgb000_22m1_2ff68ff3.zip
hbu@laptophbu2:~> jdmtool download 7
Downloading:   0%|                                                                                                                                                                     | 0.00/188M [00:00<?, ?B/s]
Traceback (most recent call last):
  File "/usr/bin/jdmtool", line 8, in <module>
    sys.exit(main())
  File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/main.py", line 440, in main
    func(**kwargs)
  File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/main.py", line 142, in cmd_download
    path = downloader.download(service, t.update)
  File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/downloader.py", line 120, in download
    expected_crc = int(service.findtext('./file_crc'), 16)
TypeError: int() can't convert non-string with explicit base
hbu@laptophbu2:~> jdmtool download 8
Downloading:   0%|                                                                                                                                                                     | 0.00/264M [00:00<?, ?B/s]
Traceback (most recent call last):
  File "/usr/bin/jdmtool", line 8, in <module>
    sys.exit(main())
  File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/main.py", line 440, in main
    func(**kwargs)
  File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/main.py", line 142, in cmd_download
    path = downloader.download(service, t.update)
  File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/downloader.py", line 120, in download
    expected_crc = int(service.findtext('./file_crc'), 16)
TypeError: int() can't convert non-string with explicit base

Any suggestions? Or is it a bug?

Many thanks for your help

Regards

Hans

**Comment by dimaryaz** [comment]
First bug report for jdmtool!

Yes, definitely a bug, but looks easy to fix. Could you try installing the `crc_fix` branch, and see if it works now? You can install it like this:

    pip install git+https://github.com/dimaryaz/jdmtool.git@crc_fix

If it does, I'll make a proper release.

Also, unrelated to this, but I'm curious: do you use a normal SD card for G1000 (rather than a special data card and a USB programmer device)? Do you have a way to program it yourself? `jdmtool transfer` will most certainly not work for you - but I'm wondering if I should add support for G1000, or if it's easy enough to just copy files to the SD card.

**Comment by dimaryaz** [comment]
Also, would you mind uploading your `~/.local/share/jdmtool/services.xml` file? You should censor anything that looks sensitive, though - there's `username`, `customer_id`, `customer_num`, `email`, `customer_name`, and, in each `service`, `customer_number`.

I'm curious why download 7 is different from the others.

**Comment by liviro411** [comment]
Hi Dima

I still get the following error message (using crc_fix):

***@***.***:~> jdmtool download 7
Downloading:   0%|


                      |
0.00/188M [00:00<?, ?B/s]
Traceback (most recent call last):
 File "/home/hbu/.local/bin/jdmtool", line 8, in <module>
   sys.exit(main())
 File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/main.py", line
440, in main
   func(**kwargs)
 File "/home/hbu/.local/lib/python3.10/site-packages/jdmtool/main.py", line
142, in cmd_download
   path = downloader.download(service, t.update)
 File
"/home/hbu/.local/lib/python3.10/site-packages/jdmtool/downloader.py", line
120, in download
   expected_crc = int(service.findtext('./file_crc'), 16)
TypeError: int() can't convert non-string with explicit base

About your question concerning the SD card: For testing I used a normal SD
card, but I have also my original Garmin SD Card.

Attached you will also find my service.

Regards

Hans


Am So., 9. Apr. 2023 um 04:09 Uhr schrieb Dima Ryazanov <
***@***.***>:

**Comment by dimaryaz** [comment]
It looks like it didn't actually install the branch - the stack trace is showing the old code. (See if you got an error from `pip`? Maybe you don't have `git` installed? It's required for installing straight from GitHub rather than pypi.)

And the file didn't get attached - I'm guessing it doesn't work with email replies, but only if you attach it directly on GitHub.

**Comment by liviro411** [comment]
Here the service.xml:

[services.zip](https://github.com/dimaryaz/jdmtool/files/11194096/services.zip)

**Comment by liviro411** [comment]
I installed your fix with:

pip install git+https://github.com/dimaryaz/jdmtool.git@crc_fix
Collecting git+https://github.com/dimaryaz/jdmtool.git@crc_fix
  Cloning https://github.com/dimaryaz/jdmtool.git (to revision crc_fix) to /tmp/pip-req-build-hqg3b7o7
  Running command git clone --filter=blob:none --quiet https://github.com/dimaryaz/jdmtool.git /tmp/pip-req-build-hqg3b7o7
  Running command git checkout -b crc_fix --track origin/crc_fix
  Zu neuem Branch 'crc_fix' gewechselt
  Branch 'crc_fix' folgt nun 'origin/crc_fix'.
  Resolved https://github.com/dimaryaz/jdmtool.git to commit 5ef1ca6fb2f91c910f80e01515d1a66108d7a2e2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: platformdirs>=2.6.2 in /usr/lib/python3.10/site-packages (from jdmtool==0.0.1) (3.2.0)
Requirement already satisfied: tqdm>=4.1.0 in /usr/lib/python3.10/site-packages (from jdmtool==0.0.1) (4.65.0)
Requirement already satisfied: requests>=2.26.0 in /usr/lib/python3.10/site-packages (from jdmtool==0.0.1) (2.28.2)
Requirement already satisfied: libusb1>=2.0.1 in /usr/lib/python3.10/site-packages (from jdmtool==0.0.1) (3.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.10/site-packages (from requests>=2.26.0->jdmtool==0.0.1) (2022.9.24)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/lib/python3.10/site-packages (from requests>=2.26.0->jdmtool==0.0.1) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests>=2.26.0->jdmtool==0.0.1) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests>=2.26.0->jdmtool==0.0.1) (1.26.15)

**Comment by dimaryaz** [comment]
Hmm, weird, that should have worked. Anyways, my fix _should_ work based on what I see in your services.xml, so I released version 0.0.2. Try `pip install -U jdmtool`, and make sure you actually get version 0.0.2. Maybe try uninstalling it if it still doesn't work?

Let me know if that fixes the download. And feel free to file new bugs :)

**Comment by liviro411** [comment]
Now I can download all database! Many thanks for your help and assistance.

Note: I will open a new issue regarding "jdmtool detect"

Am Di., 11. Apr. 2023 um 04:25 Uhr schrieb Dima Ryazanov <
***@***.***>:
