### ISSUE TITLE
Error transferring Basemap (G1000/Perspective)

### ISSUE THREAD

**Issue by aantonop** [dimaryaz/jdmtool#15]
I get the error "Missing 'next_display_version'" when attempting to transfer the basemap:
```
Extracting bmap.bin...: 100%|██████████████████████████████████████████████████████████████████████| 21.3M/21.3M [00:01<00:00, 12.9MB/s]
Extracting bmap2.bin...: 100%|█████████████████████████████████████████████████████████████████████| 21.7M/21.7M [00:01<00:00, 17.0MB/s]
Updating .jdm...
Missing 'next_display_version'
```

However, the bmap.bin and bmap2.bin files are written to the SD card successfully. I have not tested on the avionics.

**Comment by dimaryaz** [comment]
Oops, yes. I think I've fixed it - can you try installing it from git?

The avionics will probably reject the update without the fix: the `.jdm` file contains checksums of all the files, and I doubt they're optional. (Though if you have free time on your hands and want to try it anyway, I'd be curious to know what happens...)

**Comment by aantonop** [comment]
Tested and confirmed fixed:

```
Extracting bmap.bin...: 100%|██████████████████████████████████████████████████████████████████████| 21.3M/21.3M [00:01<00:00, 13.4MB/s]
Extracting bmap2.bin...: 100%|█████████████████████████████████████████████████████████████████████| 21.7M/21.7M [00:01<00:00, 17.1MB/s]
Updating .jdm...
Done
```

I currently don't have access to the avionics for the next 2 months because I am traveling. Happy to test on the actual Perspective when I return.
