### ISSUE TITLE
when reusing a thumbdrive .jdm is appended not replaced

### ISSUE THREAD

**Issue by n251ea** [dimaryaz/jdmtool#8]
when writing an Avidyne database to a thumbdrive previously used, the previous .jdm file is not overwritten rather it is appened leaving both the previous and the current databases in the file.

both the obstacle and the navdata for the same cycle need to be in the same jdm file but previous cycles should be removed before writing.

**Comment by dimaryaz** [comment]
It should've removed the old version - but I realized I didn't try it - I only tested that obstacles _don't_ remove navdata, so it's likely I have a bug.

Do you happen to know how IFD handles other regions? I.e., do they overwrite each other? Basically, I'm wondering if it should just overwrite anything with the same unique_service_id, or if it's more complicated.
